# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - mywebservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install required system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev
          sudo apt-get install -y libglib2.0-0
      - name: Create and start virtual environment
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          cd backend
          python manage.py collectstatic --noinput
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # - name: Zip artifact for deployment
      #   run: |
      #     cd backend
      #     zip release.zip ./* -r
      # - name: Upload artifact for deployment jobs
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: python-app
      #     path: |
      #       backend/release.zip
      #\       !venv/
      

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend/
            !backend/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # - name: Unzip artifact for deployment
      #   run: unzip release.zip
  

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_03DE591971E343FDB03FB6D10BCEF2F2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AF0CA476DC0464686B5171F8F43A370 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B69480C5348545C5B7337955D28A787D }}
      

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "mywebservice"
          slot-name: "Production"
          package: ./backend

      # - name: "Deploy to Azure Web App"
      #   uses: azure/webapps-deploy@v3
      #   id: deploy-to-webapp
      #   with:
      #     app-name: "mywebservice"
      #     slot-name: "Production"
